#include "../version.hpp"

/* this file is automatically generated, don't modify by hand! */

namespace doclib
{
	unsigned int version::major = 0;
	unsigned int version::minor = 1;
	unsigned int version::build = 166;
}

